Create SCHEMA companies;
Create SCHEMA geo;
Create SCHEMA messages;
Create SCHEMA photographers;
Create SCHEMA prestations;
Create SCHEMA status;
Create SCHEMA utils;
Create SCHEMA users;
Create SCHEMA notations;