<?php

namespace Main\CommonBundle\Entity\Users;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * Retrieve all roles photographers
	 * @param unknown $user
	 */
	public function getUsersByRole($role) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('u')
			->from('MainCommonBundle:Users\User', 'u')
			->where('u.roles LIKE :roles')
        	->setParameter('roles', '%"'.$role.'"%');	
		return $qb->getQuery()->getResult();
	}
	
}