security:
    role_hierarchy:
        ROLE_PHOTOGRAPHER_VERIFIED:       ROLE_PHOTOGRAPHER
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false    
        main:
            pattern: ^/
            anonymous:    true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: dashboard
            logout:
                path: fos_user_security_logout
                target: dashboard
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/devis, role: ROLE_PHOTOGRAPHER_VERIFIED }
        - { path: ^/moves, role: ROLE_PHOTOGRAPHER_VERIFIED }
        - { path: ^/availability, role: ROLE_PHOTOGRAPHER_VERIFIED }
        - { path: ^/service, role: ROLE_PHOTOGRAPHER_VERIFIED }
        - { path: ^/, role: ROLE_PHOTOGRAPHER }
