# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]         
    user.registration_listener:
        class: Main\CommunityBundle\EventListener\RegistrationListener
        arguments: []
        tags:
            - { name: kernel.event_subscriber }
    my_admin_bundle.show_user_listener:
        class: Main\CommunityBundle\EventListener\MyShowUserListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }