services:
#Form as service      
    form_company:
        class: "Main\CommonBundle\Form\Companies\FormCompanyType"
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: form.type, alias: form_company }
    form_iban:
        class: "Main\CommonBundle\Form\Companies\FormIbanType"
        arguments: []
        tags:
            - { name: form.type, alias: form_iban }
    form_presentation:
        class: "Main\CommonBundle\Form\Users\FormPresentationType"
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: form_presentation }
    form_security:
        class: "Main\CommonBundle\Form\Users\FormSecurityType"
        arguments: [@security.context, @security.password_encoder ]
        tags:
            - { name: form.type, alias: form_security }
    form_create_admin:
        class: "Main\CommonBundle\Form\Users\FormCreateAdminType"
        arguments: []
        tags:
            - { name: form.type, alias: form_create_admin }
    form_confirm_company:
        class: "Main\CommonBundle\Form\Companies\FormConfirmCompanyType"
        tags:
            - { name: form.type, alias: form_confirm_company }
    form_devis:
        class: "Main\CommonBundle\Form\Offers\FormDevisType"
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: form.type, alias: form_devis }
    form_devis_prices:
        class: "Main\CommonBundle\Form\Offers\FormDevisPricesType"
        arguments: [@doctrine.orm.entity_manager, @security.context]
        tags:
            - { name: form.type, alias: form_devis_prices }
    form_devis_book:
        class: "Main\CommonBundle\Form\Offers\FormDevisBookType"
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: form_devis_book }
    form_moves:
        class: "Main\CommonBundle\Form\Offers\FormMovesType"
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: form_moves }
    form_front_search:
        class: "Main\CommonBundle\Form\Front\FormSearch"
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: form.type, alias: form_front_search }
    form_front_devis_book:
        class: "Main\CommonBundle\Form\Front\FormDevisBook"
        arguments: [@session]
        tags:
            - { name: form.type, alias: form_front_devis_book }
    form_message:
        class: "Main\CommonBundle\Form\Messages\FormMessageType"
        arguments: []
        tags:
            - { name: form.type, alias: form_message }
    form_transaction:
        class: "Main\CommonBundle\Form\Transactions\FormTransactionType"
        arguments: []
        tags:
            - { name: form.type, alias: form_transaction }
    form_client_notation:
        class: "Main\CommonBundle\Form\Evaluations\FormClientNotationType"
        arguments: []
        tags:
            - { name: form.type, alias: form_client_notation }
    form_photographer_notation:
        class: "Main\CommonBundle\Form\Evaluations\FormPhotographerNotationType"
        arguments: []
        tags:
            - { name: form.type, alias: form_photographer_notation }
    form_evaluation:
        class: "Main\CommonBundle\Form\Evaluations\FormEvaluationType"
        arguments: [@security.context]
        tags:
            - { name: form.type, alias: form_evaluation }
    form_commission:
        class: "Main\CommonBundle\Form\Commissions\FormCommissionType"
        arguments: []
        tags:
            - { name: form.type, alias: form_commission }
    form_commission_prestation:
        class: "Main\CommonBundle\Form\Commissions\FormCommissionPrestationType"
        arguments: []
        tags:
            - { name: form.type, alias: form_commission_prestation }