imports:
    - { resource: forms.yml }
services:
#services
    service_preference_emails:
        class: "Main\CommonBundle\Services\Users\ServiceEmail"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_email:
        class: "Main\CommonBundle\Services\Emails\ServiceEmail"
        arguments: [@mailer, @twig, @translator.default, @service_preference_emails, "%link_community%", "%link_front%"]
    service_reference:
        class: "Main\CommonBundle\Services\Services\ServiceReference"
        arguments: []
    service_session:
        class: "Main\CommonBundle\Services\Session\ServiceSession"
        arguments: [@session]
    service_town:
        class: "Main\CommonBundle\Services\Geo\ServiceTown"
        arguments: [@doctrine.orm.entity_manager]
    service_department:
        class: "Main\CommonBundle\Services\Geo\ServiceDepartment"
        arguments: [@doctrine.orm.entity_manager, "@logger"]
    service_commission:
        class: "Main\CommonBundle\Services\Commission\ServiceCommission"
        arguments: [@doctrine.orm.entity_manager, @service_session, "@logger"]
    service_notification:
        class: "Main\CommonBundle\Services\Messages\ServiceNotification"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_user:
        class: "Main\CommonBundle\Services\Users\ServiceUser"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "%upload_pp_path%", "@logger"]
    service_devis:
        class: "Main\CommonBundle\Services\Offers\ServiceDevis"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_prices:
        class: "Main\CommonBundle\Services\Offers\ServicePrices"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_devis_book:
        class: "Main\CommonBundle\Services\Offers\ServiceDevisBook"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "%upload_devis_path%", "@logger"]
    service_moves_radius:
        class: "Main\CommonBundle\Services\Offers\ServiceMovesRadius"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_availability:
        class: "Main\CommonBundle\Services\Offers\ServiceAvailability"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session]
    service_search:
        class: "Main\CommonBundle\Services\Search\ServiceSearch"
        arguments: [@doctrine.orm.entity_manager, @security.context, "@logger"]
        tags:
            - { name: monolog.logger, channel: search }
    service_prestation_commission:
        class: "Main\CommonBundle\Services\Services\ServiceCommission"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger", @service_commission]
    service_prestation:
        class: "Main\CommonBundle\Services\Services\ServicePrestation"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_reference, @service_email, @service_session, "@logger", @service_prestation_commission, @service_notification]
    service_notation:
        class: "Main\CommonBundle\Services\Services\ServiceNotation"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, @service_devis, @service_user, "@logger"]
    service_message:
        class: "Main\CommonBundle\Services\Messages\ServiceMessage"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_email, "@logger"]
    service_company:
        class: "Main\CommonBundle\Services\Companies\ServiceCompany"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_email, "@logger"]
    service_iban:
        class: "Main\CommonBundle\Services\Companies\ServiceIban"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_session, "@logger"]
    service_transaction:
        class: "Main\CommonBundle\Services\Transactions\ServiceTransaction"
        arguments: [@doctrine.orm.entity_manager, @security.context, @service_prestation, @service_session, "@logger"]
#Listeners
    listener_moves_radius:
        class: Main\CommonBundle\Listener\MoveRadiusListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_company:
        class: Main\CommonBundle\Listener\CompanyListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_iban:
        class: Main\CommonBundle\Listener\IbanListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_devis:
        class: Main\CommonBundle\Listener\DevisListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_devis_prices:
        class: Main\CommonBundle\Listener\DevisPricesListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_devis_book:
        class: Main\CommonBundle\Listener\DevisBookListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_prestation:
        class: Main\CommonBundle\Listener\PrestationListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_email:
        class: Main\CommonBundle\Listener\EmailListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_message:
        class: Main\CommonBundle\Listener\MessageListener
        tags:
            - { name: doctrine.orm.entity_listener }
    listener_notification:
        class: Main\CommonBundle\Listener\NotificationListener
        tags:
            - { name: doctrine.orm.entity_listener }
#Extension
    twig_base64:
        class: "Main\CommonBundle\Services\Extensions\TwigImage64"
        arguments: ["%upload_pp_path%", "%upload_devis_path%"]
        tags:
            - { name: "twig.extension"}
    Twig_Data_Request:
        class: "Main\CommonBundle\Services\Extensions\TwigDataRequest"
        arguments: [@doctrine.orm.entity_manager, @security.context, @translator.default]
        tags:
            - { name: "twig.extension"}
#Handlers
    redirect.after.login:
        class: Main\CommonBundle\Redirection\AfterLoginRedirection
        arguments: [@router, @service_session]