<?php

namespace Main\CommonBundle\Entity\Photographers;

use Doctrine\ORM\EntityRepository;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends EntityRepository
{
	
	/**
	 * 
	 * @param unknown $company
	 */
	public function getDates($company)
	{		
		$qb = $this->_em->createQueryBuilder();
		$qb->select('a.day')
			->from('MainCommonBundle:Photographers\availability', 'a')
			->where('a.company = :company')
			->setParameter('company', $company);
		$query = $qb->getQuery();
		$query->setResultCacheId('getAvailability_'.$company);
		$query->useQueryCache(true);
		$query->useResultCache(true, 21600, 'getAvailability_'.$company);
		return $query->getResult();
	}
	
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function updateDates($company, $dates) {
		$this->_em->getConnection()->delete('photographers.availability', array('company' => $company));
		$this->createDates($company, $dates);
		
	}
	
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function createDates($company, $dates)
	{
		$now = new \DateTime('now');
		$cacheDriver = $this->_em->getConfiguration()->getResultCacheImpl();
        $cacheDriver->delete('getAvailability_'.$company);
		foreach ($dates as $date)
		{
		$this->_em->getConnection()->insert('photographers.availability', array(
				'company' 	=> $company, 
				'day' 		=> $date,
				'createdAt'	=> $now->format('Y-m-d H:i:s')
				));	
		}
	}	
}
