<?php

namespace Main\CommonBundle\Entity\Photographers;

use Doctrine\ORM\EntityRepository;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvailabilityRepository extends EntityRepository
{
	
	/**
	 * 
	 * @param unknown $company
	 */
	public function getDates($company)
	{		
		return $this->_em->getConnection()->fetchAll('select day from photographers.availability where company = ?', array($company));
	}
	
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function updateDates($company, $dates) {
		$this->_em->getConnection()->delete('photographers.availability', array('company' => $company));
		$this->createDates($company, $dates);
		
	}
	
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function createDates($company, $dates)
	{
		$now = new \DateTime('now');
		foreach ($dates as $date)
		{
		$this->_em->getConnection()->insert('photographers.availability', array(
				'company' 	=> $company, 
				'day' 		=> $date,
				'createdAt'	=> $now->format('Y-m-d H:i:s')
				));	
		}
	}
	
}
