<?php

namespace Main\CommonBundle\Entity\Photographers;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevisPricesRepository extends EntityRepository
{
	/**
	 * [getPricesByDuration description]
	 * @param  [type] $devis [description]
	 * @return [type]        [description]
	 */
	public function getPricesByDuration($devis)
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('p.price as price', 'd.id')
			->from('MainCommonBundle:Photographers\DevisPrices', 'p')
			->leftjoin('p.duration', 'd')
			->where('p.devis = :devis')
			->setParameter('devis', $devis);
		$query = $qb->getQuery();
		$query->setResultCacheId('getPricesByDuration'.$devis);
		$query->useQueryCache(true);
		return $query->getResult();
	}
	
}
