<?php

namespace Main\CommonBundle\Entity\Photographers;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveRadiusRepository extends EntityRepository
{
	
	/**
	 * 
	 * @param unknown $categoryId
	 * @param unknown $townId
	 * @param unknown $day
	 */
	public function getRadius($company) {
		$qb = $this->_em->createQueryBuilder();
		$qb->select('m')
			->from('MainCommonBundle:Photographers\MoveRadius', 'm')
			->where('m.company = :company')
			->setParameter('company', $company);
		$query = $qb->getQuery();
		$query->useQueryCache(true);
		return $query->getSingleResult();
	}
	
	
}
