<?php

namespace Main\CommonBundle\Entity\Photographers;

use Doctrine\ORM\EntityRepository;

/**
 * MoveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoveRepository extends EntityRepository
{
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function updateMoves($company, $moves) {
		$this->_em->getConnection()->delete('photographers.moves', array('company' => $company));
		$this->createMoves($company, $moves);
		
	}
	
	/**
	 * 
	 * @param unknown $company
	 * @param unknown $moves
	 */
	public function createMoves($company, $moves)
	{
		$date = new \DateTime('now');
		foreach ($moves as $town)
		{
		$this->_em->getConnection()->insert('photographers.moves', array(
				'company' 	=> $company, 
				'town' 		=> $town['id'],
				'createdAt'	=> $date->format('Y-m-d H:i:s')
				));	
		}
	}
	
}
