security:
    role_hierarchy:
        ROLE_SUPER_ADMIN:       ROLE_ADMIN
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false    
        main:
            pattern: ^/
            anonymous:    true
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: dashboard
            logout:
                path: fos_user_security_logout
                target: dashboard
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY  }
        - { path: ^/create-user, role: ROLE_SUPER_ADMIN }
        - { path: ^/disable-user, role: ROLE_SUPER_ADMIN }
        - { path: ^/geo, role: ROLE_SUPER_ADMIN }
        - { path: ^/commission, role: ROLE_SUPER_ADMIN }
        - { path: ^/, role: ROLE_ADMIN }
