<?php

namespace Main\CommonBundle\Entity\Messages;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageRepository extends EntityRepository
{
	/**
	 * Ajout des messages d'historique
	 * @param  int $id       [description]
	 * @param  int $status   [description]
	 * @param  int $sender   [description]
	 * @param  int $receiver [description]
	 * @param  int $message  [description]
	 * @return string           [description]
	 */
	public function createMessagePrestation($prestation, $type, $sender, $receiver, $message)
	{

		$date = new \DateTime('now');
		$this->_em->getConnection()->insert('messages.message', array(
				'sender' 		=> $sender,
				'receiver' 		=> $receiver,
				'type' 			=> $type,
				'prestation' 	=> $prestation,
				'read' 			=> 1,
				'content' 		=> $message,
				'createdAt'		=> $date->format('Y-m-d H:i:s'),
				'updatedAt' 	=> $date->format('Y-m-d H:i:s'),
				));	
	}
	
}