<?php

namespace Main\CommonBundle\Entity\Utils;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	/**
	 * [findCommissions description]
	 * @return [type] [description]
	 */
	public function findAllCategories()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('c')
			->from('MainCommonBundle:Utils\Category', 'c');
		$query = $qb->getQuery();
		$query->setResultCacheId('findAllCategories');
		$query->useQueryCache(true);
		$query->useResultCache(true);
		$query->useResultCache(true, 86400, 'findAllCategories');
		return $query->getResult();
	}

	/**
	*/
    public function findCategoryFront()
    {
    	$qb = $this->_em->createQueryBuilder();
		$qb->select('c')
			->from('MainCommonBundle:Utils\Category', 'c')
			->where('c.active = :id')
			->setParameter('id', 1);
		$query = $qb->getQuery();
		$query->setResultCacheId('findCategoryFront');
		$query->useQueryCache(true);
		$query->useResultCache(true);
		$query->useResultCache(true, 86400, 'findCategoryFront');
		return $query->getSingleResult();
    } 	
}