<?php

namespace Main\CommonBundle\Entity\Utils;

use Doctrine\ORM\EntityRepository;

/**
 * CommuneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissionRepository extends EntityRepository
{
	/**
	 * [findCommissions description]
	 * @return [type] [description]
	 */
	public function findCommissions()
	{
		$qb = $this->_em->createQueryBuilder();
		$qb->select('c')
			->from('MainCommonBundle:Utils\Commission', 'c');
		$query = $qb->getQuery();
		$query->setResultCacheId('findCommissions');
		$query->useQueryCache(true);
		$query->useResultCache(true);
		$query->useResultCache(true, 86400, 'findCommissions');
		return $query->getResult();
	}

	/**
	*/
    public function findCommissionParticuliers()
    {
    	$qb = $this->_em->createQueryBuilder();
		$qb->select('c')
			->from('MainCommonBundle:Utils\Commission', 'c')
			->where('c.id = :id')
			->setParameter('id', 1);
		$query = $qb->getQuery();
		$query->setResultCacheId('findCommissionParticuliers');
		$query->useQueryCache(true);
		$query->useResultCache(true);
		$query->useResultCache(true, 86400, 'findCommissionParticuliers');
		return $query->getSingleResult();
    } 

    /**
     * [findCommissionEntreprises description]
     * @return [type] [description]
     */
    public function findCommissionEntreprises()
    {
    	$qb = $this->_em->createQueryBuilder();
		$qb->select('c')
			->from('MainCommonBundle:Utils\Commission', 'c')
			->where('c.id = :id')
			->setParameter('id', 2);
		$query = $qb->getQuery();
		$query->setResultCacheId('findCommissionEntreprises');
		$query->useQueryCache(true);
		$query->useResultCache(true);
		$query->useResultCache(true, 86400, 'findCommissionEntreprises');
		return $query->getSingleResult();
    } 
	
}